export enum Drivers {
	Verstappen = 'Verstappen',
	Perez = 'Perez',
	Hamilton = 'Hamilton',
	Russell = 'Russell',
	Leclerc = 'Leclerc',
	Sainz = 'Sainz',
	Norris = 'Norris',
	Ricciardo = 'Ricciardo',
	Gasly = 'Gasly',
	Tsunoda = 'Tsunoda',
	Ocon = 'Ocon',
	Alonso = 'Alonso',
	Bottas = 'Bottas',
	Guanyu = 'Guanyu',
	Stroll = 'Stroll',
	Vettel = 'Vettel',
	Magnussen = 'Magnussen',
	Schumacher = 'Schumacher',
	Albon = 'Albon',
	Latifi = 'Latifi',
}
